CREATE TABLE personas(id int PRIMARY KEY,nombre varchar(200) NOT NULL);
INSERT INTO PUBLIC.PERSONAS (ID, NOMBRE) VALUES(0, 'p1');
INSERT INTO PUBLIC.PERSONAS (ID, NOMBRE) VALUES(1, 'p2');
INSERT INTO PUBLIC.PERSONAS (ID, NOMBRE) VALUES(2, 'p3');
INSERT INTO PUBLIC.PERSONAS (ID, NOMBRE) VALUES(4, 'p4');